version: '3.10'

services:
  web:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo

  worker:
    build: .
    command: celery -A src.core.celery_config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
      - mongo

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:latest"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
    driver: local
